### ISSUE TITLE
error plugin dont load

### ISSUE THREAD

**Issue by Toketo1442** [jdevs-mc/ChristmasGifts#1]
[01:35:29 ERROR]: Command exception: /christmas
org.bukkit.command.CommandException: Cannot execute command 'christmas' in plugin ChristmasGifts v1.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1624) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Toketo1442** [comment]
[01:34:04] [Server thread/INFO]: [ChristmasGifts] Enabling ChristmasGifts v1.1
[01:34:04] [Server thread/ERROR]: Error occurred while enabling ChristmasGifts v1.1 (Is it up to date?)
java.lang.NumberFormatException: For input string: "21-2284-4e55e26 (MC: 1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at ChristmasGifts.jar/dev.jdevs.JGifts.utils.Message.hex(Message.java:23) ~[ChristmasGifts.jar:?]
	at ChristmasGifts.jar/dev.jdevs.JGifts.utils.Message.sendLogger(Message.java:85) ~[ChristmasGifts.jar:?]
	at ChristmasGifts.jar/dev.jdevs.JGifts.Christmas.onEnable(Christmas.java:73) ~[ChristmasGifts.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:34:04] [Server thread/INFO]: [ChristmasGifts] Disabling ChristmasGifts v1.1

**Comment by mitriyf** [comment]
Hello. I looked at your request and saw the problem, I will try to solve it in my own way or yours from the requests.

**Comment by mitriyf** [comment]
Hello again. I fixed the code, but decided to do without versions 1.x, which contain bugs. The plugin can be used on 1.8.8, 1.7.10, but not on simple 1.7. For versions below 1.10, an additional argument 1.x.y is required.

If there is a problem, please report it again, I will be happy to listen to any criticism about the plugin.
