### ISSUE TITLE
a problem with the config.yml (en/ru)

### ISSUE THREAD

**Issue by Toketo1442** [jdevs-mc/ChristmasGifts#3]
[21:27:07 WARN]: java.nio.file.NoSuchFileException: plugins/ChristmasGifts/en\config.yml
[21:27:07 WARN]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[21:27:07 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[21:27:07 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[21:27:07 WARN]:        at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:886)
[21:27:07 WARN]:        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
[21:27:07 WARN]:        at java.base/java.nio.file.Files.move(Files.java:1430)
[21:27:07 WARN]:        at ChristmasGifts (3).jar//dev.jdevs.JGifts.Christmas.onEnable(Christmas.java:119)
[21:27:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[21:27:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:27:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:27:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[21:27:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[21:27:07 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[21:27:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[21:27:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[21:27:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[21:27:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[21:27:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[21:27:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:27:07 WARN]: The creation of the config.yml file was incorrect, please contact the administrator.
[21:27:07 ERROR]: Error occurred while enabling ChristmasGifts v1.1.1 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/.paper-remapped/ChristmasGifts (3).jar
at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:215) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at ChristmasGifts (3).jar/dev.jdevs.JGifts.utils.ConfigManager.of(ConfigManager.java:26) ~[ChristmasGifts (3).jar:?]
at ChristmasGifts (3).jar/dev.jdevs.JGifts.Christmas.onEnable(Christmas.java:152) ~[ChristmasGifts (3).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:27:07 INFO]: [ChristmasGifts] Disabling ChristmasGifts v1.1.1
[21:27:07 ERROR]: Error occurred while disabling ChristmasGifts v1.1.1
java.lang.ExceptionInInitializerError: null
at ChristmasGifts (3).jar/dev.jdevs.JGifts.Christmas.onDisable(Christmas.java:210) ~[ChristmasGifts (3).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getBoolean(String)" because "dev.jdevs.JGifts.utils.Configurations.launch" is null
at ChristmasGifts (3).jar/dev.jdevs.JGifts.Settings.<clinit>(Settings.java:11) ~[ChristmasGifts (3).jar:?]
... 16 more

**Comment by Toketo1442** [comment]
I tested the RU and EN, and this is happening

**Comment by mitriyf** [comment]
This is strange, the plugin should not cause such problems. I will study this problem.

**Comment by mitriyf** [comment]
A temporary solution to the problem:
Take from .open the jar via Winrar or another convenient method and take the file configuration from en/ru and move it to the plugin folder.

**Comment by mitriyf** [comment]
Thank you for helping me find this problem! This is fixed in 1.1.2-RELEASE.
I fixed the plugin on Linux, it was related to the directory search \
